services:
  db:
    image: postgres:17
    container_name: receptionist_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: receptionist_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      GIN_MODE: ${GIN_MODE}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    command: sh -c "migrate -path /migrations -database $DATABASE_URL up && /Medical-Portal"

volumes:
  postgres-data: {}